package ja3proxy

import "time"

type RunningConfig struct {
	CaptureTLS             bool
	CaptureTCPInterface    string
	ListCaptureInterfaces  bool
	CaptureRaw             bool
	TLSKeyLogFile          string
	CaptureJSONL           string
	CaptureSQLite          string
	CaptureSQLiteRetention int
	StateSQLite            string
	CaptureSpool           string
	CaptureSpoolKey        string
	CaptureSpoolMaxBytes   int64
	CaptureSpoolKeyMaxAge  time.Duration
	AuditLog               string
	AuditSQLite            string
	DeviceMapFile          string
	TLSMode                string
	TLSTemplateFile        string
	DumpTraffic            bool
	LogLevel               string
	Listen                 string
	Addr                   string
	Port                   string
	TLSVersion             string
	TLSClient              string
	TLSFingerprintExplicit bool
	ListFingerprints       bool
	FingerprintConfig      string
	UpstreamTLSConfig      string
	RouteConfigFile        string
	Cert                   string
	Key                    string
	Upstream               string
	ProxyUsername          string
	ProxyPassword          string
	ProxyUsernameFile      string
	ProxyPasswordFile      string
	TUI                    bool
	WebPanel               string
	WebPanelTokenFile      string
	WebPanelCert           string
	WebPanelKey            string
	ProxyProtocol          string
}
